service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-auto-swagger
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  environment:
    REGION: eu-west-1
    PRODUCTS_TABLE: products
    STOCK_TABLE: stock
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:654654310466:table/products"
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:654654310466:table/stock"



functions:
  getProductsList:
    handler: ./functions/get-products-list/get-products-list.getProductsList
    events:
      - http:
          method: get
          path: /products
          cors:
            origin: '*'
            headers:
              - Content-Type
  getProductsById:
    handler: ./functions/get-product-by-id/get-product-by-id.getProductsById
    events:
      - http:
          method: get
          path: /products/{productId}
          cors:
            origin: '*'
            headers:
              - Content-Type
          responseData: {
            200: {
              description: "Returns product info"
            },
            500: {
              description: "Product not found"
            }
          }
  createProduct:
    handler: ./functions/create-product/create-product.createProduct
    events:
      - http:
          method: post
          path: products
          cors:
            origin: '*'
            headers:
              - Content-Type

custom:
  autoswagger:
    host: "mo80kwrt0d.execute-api.eu-west-1.amazonaws.com/dev/"
    schemes: ['https']
